### ISSUE TITLE
Specification compliance tracking

### ISSUE THREAD

**Issue by Majored** [Majored/rs-async-zip#6]
## Structure
- [x] Appropriate representations of headers
- [x] Appropriate header delimiter constants  
- [x] Reading local file headers
- [x] Writing local file headers
- [x] Reading central directory headers
- [x] Writing central directory headers
- [x] Reading entry names & extra fields
- [x] Writing entry names & extra fields
- [x] Reading central directory entry comment
- [x] Writing central directory entry comment
- [x] Reading ending file comment
- [x] Writing ending file comment

##  Features
- [x] Reading entries with data descriptors
- [x] Writing entries with data descriptors
- [ ] Reading entries with data descriptors (without de facto delimiter)
- [ ] Writing entries with data descriptors (without de facto delimiter)
- [ ] Versioning for reading
- [x] Versioning for writing
- [ ] ZIP64 for reading
- [ ] ZIP64 for writing
- [ ] Encryption for reading
- [ ] Encryption for writing

**Comment by damccull** [comment]
Howdy. Just found your crate. Looks very promising. I'm particularly interested in the encryption part, though I'll not rush you. Your crate seems to be the best maintained at the moment, and the only one openly attempting to meet spec. I'm super excited.

**Comment by Majored** [comment]
Thank you very much. :)

I wasn't planning to include encryption in actual versions of the crate for a fair while, but I could certainly make a branch to start on it and see how it goes. Did you need it for both reading & writing, or just one of them?

**Comment by damccull** [comment]
I personally only need it for reading at the moment but I'm not in a hurry.

**Comment by thomassa** [comment]
Does it support reading a "split" zip file, as described in section 8 of the [specification](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT)?
(E.g. `file.z01`, `file.z02`, `file.zip`)

**Comment by Majored** [comment]
@thomassa Never saw your message, sorry about that. I wasn't planning on supporting it as it seems like quite an outdated feature and not one that I've personally used over the years. Though, I wouldn't be against it down the line.

I'm closing this anyway as I haven't been using this to really track progress - I've just kept a mental note of everything really.
